$axure.loadCurrentPage({
  "url":"新页面_2.html",
  "generationDate":new Date(1402239529782.78),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1c16dd54dfbc4f4daa3bef32f4cd657e",
    "type":"Axure:Page",
    "name":"新页面 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6140143d17b04bbb8823afb2fefcbd80",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":10},
            "size":{
              "width":540,
              "height":370}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb123652b0d642fcb350c74078fe4165",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":10},
                "size":{
                  "width":540,
                  "height":370}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_促销板块/u0.png"}},
{
          "id":"d263bba41e4d4f7296cf0b8c5c32f968",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":50},
            "size":{
              "width":470,
              "height":260}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0b92711958d4d04920977a9a3a81f64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":50},
                "size":{
                  "width":470,
                  "height":260}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_2/u2.png"}},
{
          "id":"98853c34c73946e1b17484789faf8d8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":370,
              "y":62},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b99c9ab1ad7f4a788349dae8b76b8acd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":370,
                  "y":62},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abe63039d7b645d3845409e99bf84e5b",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":110},
            "size":{
              "width":390,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de2e9bab8c3e4c9a8cab3573c91201fe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0b7c3f360ac841b0a2064dd7990e8454",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u7.png"}},
{
              "id":"ac8cd5731e8842d9a385965eb210c034",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b0bf2c262ede4a3a92e309eb07043bc0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u7.png"}},
{
              "id":"b9010039af7b4dcc912f62d65a80a19f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"072dc552aefe4214ad4703626d287900",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u7.png"}},
{
              "id":"a0ddcc58dad9425e88797bf01a964c0c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":0},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d9cfb51e0fae458a8af675d10dc4fbef",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":0},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_1/u11.png"}},
{
              "id":"9f12f8f4ebb046bfa80fd9ccb302ce07",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":30},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"181f78eab9f545bdaac009e320567cbb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":30},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_1/u11.png"}},
{
              "id":"a2de35ce1ebc472eafe334c51d35b4e3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":60},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8b19f1e4eff04276a69431bac84f7cc7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":60},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_1/u11.png"}},
{
              "id":"b33cfc018ccf4c49a207e0e03e243177",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":169,
                  "y":0},
                "size":{
                  "width":47,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0cd9523cec5a4f43a1230b7562cd9925",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":169,
                      "y":0},
                    "size":{
                      "width":47,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u11.png"}},
{
              "id":"b7092b076a2e4f628adc443112b3442c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":169,
                  "y":30},
                "size":{
                  "width":47,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8c5bc1e1019046649fde65350c7dff0c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":169,
                      "y":30},
                    "size":{
                      "width":47,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u11.png"}},
{
              "id":"3497e2b42017425a9d64f18c222e33a2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":169,
                  "y":60},
                "size":{
                  "width":47,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"25fdc3005e1144698cc4655cdd995d92",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":169,
                      "y":60},
                    "size":{
                      "width":47,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u11.png"}},
{
              "id":"779e4936fe4e4315842d2b66349caddc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":0},
                "size":{
                  "width":65,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c1f7d3cf7183499d956fff3f5cbd0b46",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":0},
                    "size":{
                      "width":65,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u15.png"}},
{
              "id":"77766b36f3c84ff4ae5a109fc4ae2605",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":30},
                "size":{
                  "width":65,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"58aaede6e0494ac7a304c1bd8a797711",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":30},
                    "size":{
                      "width":65,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u15.png"}},
{
              "id":"dfb2d919b5bf4067b478ebb13a7207bf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":60},
                "size":{
                  "width":65,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4fe203bfc48249ca84d0245ad9371bb5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":60},
                    "size":{
                      "width":65,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u15.png"}},
{
              "id":"603b76ab20554f4084c5d0f943bd469c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":216,
                  "y":0},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c9fc7c131b7643f992c6c5cf2a5b46b5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":216,
                      "y":0},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_1/u11.png"}},
{
              "id":"0836b2e7922946ad94b97b6223a53cf5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":216,
                  "y":30},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1e2261407af048a8b6cc7905328779bb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":216,
                      "y":30},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_1/u11.png"}},
{
              "id":"5eb81fda39fd4257880a587b0c105b89",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":216,
                  "y":60},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8b49444c7dbc46448458f2cb734efada",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":216,
                      "y":60},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_1/u11.png"}},
{
              "id":"10a61ab287a24ca5a98bb7212c015f22",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":324,
                  "y":0},
                "size":{
                  "width":66,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0ebda848f31d48d18d513033ff89586c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":324,
                      "y":0},
                    "size":{
                      "width":66,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u17.png"}},
{
              "id":"c5c0a3a6f6a2499687729e8b236f6175",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":324,
                  "y":30},
                "size":{
                  "width":66,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4899aea4e7ef4f1daee60d0c487ffc1f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":324,
                      "y":30},
                    "size":{
                      "width":66,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u17.png"}},
{
              "id":"eb1eebfbcf1f410f914baaae5f4f95d9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":324,
                  "y":60},
                "size":{
                  "width":66,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2b49f5aa531b4134a94e6d4129ae75ee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":324,
                      "y":60},
                    "size":{
                      "width":66,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u17.png"}},
{
              "id":"98f3bc7855994dd695f6167b60f426d3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e0d49a1ab3f34fb6a7915fcdd80164ff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u43.png"}},
{
              "id":"1fd0f8c44bea41ccb0902ff7b34543da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":90},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a3abae3c184141c88dfc18e9535375e0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":90},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_1/u35.png"}},
{
              "id":"01c7da751692410d89fb900ea7b70df3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":169,
                  "y":90},
                "size":{
                  "width":47,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ec51cae577f441b2b2386caf44ef99b8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":169,
                      "y":90},
                    "size":{
                      "width":47,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u47.png"}},
{
              "id":"698bc46882ac436b81565e7af6dcc33d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":216,
                  "y":90},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"439fc5fb268f475386b9ea2598632c4b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":216,
                      "y":90},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_1/u35.png"}},
{
              "id":"ce6b320b117443758aa362b342d8d6a3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":90},
                "size":{
                  "width":65,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"03712445b0004748bcd801dcd204d881",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":90},
                    "size":{
                      "width":65,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u51.png"}},
{
              "id":"c3370faa3ea149619f9fce3b509cb3ec",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":324,
                  "y":90},
                "size":{
                  "width":66,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a9280f3f33eb47d4a9796dbc07f5f7de",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":324,
                      "y":90},
                    "size":{
                      "width":66,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u53.png"}}]},
{
          "id":"7f41ef92ff4a41ba87e54f10daf90b28",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":557,
              "y":143},
            "size":{
              "width":41,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"047e21828fc944a98121baad74bab091",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":557,
              "y":173},
            "size":{
              "width":41,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"18473e5d5e984b38a863072f2a60c19e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":557,
              "y":203},
            "size":{
              "width":41,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"789da28de474452784faaf16091270aa",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":288.5,
              "y":245},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 新页面 3 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"新页面_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"85073eeb15a74ab281b0d75675c55a53",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":431.5,
              "y":245},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 新页面 2 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"新页面_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "6140143d17b04bbb8823afb2fefcbd80":{
      "scriptId":"u0"},
    "fb123652b0d642fcb350c74078fe4165":{
      "scriptId":"u1"},
    "d263bba41e4d4f7296cf0b8c5c32f968":{
      "scriptId":"u2"},
    "f0b92711958d4d04920977a9a3a81f64":{
      "scriptId":"u3"},
    "98853c34c73946e1b17484789faf8d8d":{
      "scriptId":"u4"},
    "b99c9ab1ad7f4a788349dae8b76b8acd":{
      "scriptId":"u5"},
    "abe63039d7b645d3845409e99bf84e5b":{
      "scriptId":"u6"},
    "de2e9bab8c3e4c9a8cab3573c91201fe":{
      "scriptId":"u7"},
    "0b7c3f360ac841b0a2064dd7990e8454":{
      "scriptId":"u8"},
    "a0ddcc58dad9425e88797bf01a964c0c":{
      "scriptId":"u9"},
    "d9cfb51e0fae458a8af675d10dc4fbef":{
      "scriptId":"u10"},
    "b33cfc018ccf4c49a207e0e03e243177":{
      "scriptId":"u11"},
    "0cd9523cec5a4f43a1230b7562cd9925":{
      "scriptId":"u12"},
    "603b76ab20554f4084c5d0f943bd469c":{
      "scriptId":"u13"},
    "c9fc7c131b7643f992c6c5cf2a5b46b5":{
      "scriptId":"u14"},
    "779e4936fe4e4315842d2b66349caddc":{
      "scriptId":"u15"},
    "c1f7d3cf7183499d956fff3f5cbd0b46":{
      "scriptId":"u16"},
    "10a61ab287a24ca5a98bb7212c015f22":{
      "scriptId":"u17"},
    "0ebda848f31d48d18d513033ff89586c":{
      "scriptId":"u18"},
    "ac8cd5731e8842d9a385965eb210c034":{
      "scriptId":"u19"},
    "b0bf2c262ede4a3a92e309eb07043bc0":{
      "scriptId":"u20"},
    "9f12f8f4ebb046bfa80fd9ccb302ce07":{
      "scriptId":"u21"},
    "181f78eab9f545bdaac009e320567cbb":{
      "scriptId":"u22"},
    "b7092b076a2e4f628adc443112b3442c":{
      "scriptId":"u23"},
    "8c5bc1e1019046649fde65350c7dff0c":{
      "scriptId":"u24"},
    "0836b2e7922946ad94b97b6223a53cf5":{
      "scriptId":"u25"},
    "1e2261407af048a8b6cc7905328779bb":{
      "scriptId":"u26"},
    "77766b36f3c84ff4ae5a109fc4ae2605":{
      "scriptId":"u27"},
    "58aaede6e0494ac7a304c1bd8a797711":{
      "scriptId":"u28"},
    "c5c0a3a6f6a2499687729e8b236f6175":{
      "scriptId":"u29"},
    "4899aea4e7ef4f1daee60d0c487ffc1f":{
      "scriptId":"u30"},
    "b9010039af7b4dcc912f62d65a80a19f":{
      "scriptId":"u31"},
    "072dc552aefe4214ad4703626d287900":{
      "scriptId":"u32"},
    "a2de35ce1ebc472eafe334c51d35b4e3":{
      "scriptId":"u33"},
    "8b19f1e4eff04276a69431bac84f7cc7":{
      "scriptId":"u34"},
    "3497e2b42017425a9d64f18c222e33a2":{
      "scriptId":"u35"},
    "25fdc3005e1144698cc4655cdd995d92":{
      "scriptId":"u36"},
    "5eb81fda39fd4257880a587b0c105b89":{
      "scriptId":"u37"},
    "8b49444c7dbc46448458f2cb734efada":{
      "scriptId":"u38"},
    "dfb2d919b5bf4067b478ebb13a7207bf":{
      "scriptId":"u39"},
    "4fe203bfc48249ca84d0245ad9371bb5":{
      "scriptId":"u40"},
    "eb1eebfbcf1f410f914baaae5f4f95d9":{
      "scriptId":"u41"},
    "2b49f5aa531b4134a94e6d4129ae75ee":{
      "scriptId":"u42"},
    "98f3bc7855994dd695f6167b60f426d3":{
      "scriptId":"u43"},
    "e0d49a1ab3f34fb6a7915fcdd80164ff":{
      "scriptId":"u44"},
    "1fd0f8c44bea41ccb0902ff7b34543da":{
      "scriptId":"u45"},
    "a3abae3c184141c88dfc18e9535375e0":{
      "scriptId":"u46"},
    "01c7da751692410d89fb900ea7b70df3":{
      "scriptId":"u47"},
    "ec51cae577f441b2b2386caf44ef99b8":{
      "scriptId":"u48"},
    "698bc46882ac436b81565e7af6dcc33d":{
      "scriptId":"u49"},
    "439fc5fb268f475386b9ea2598632c4b":{
      "scriptId":"u50"},
    "ce6b320b117443758aa362b342d8d6a3":{
      "scriptId":"u51"},
    "03712445b0004748bcd801dcd204d881":{
      "scriptId":"u52"},
    "c3370faa3ea149619f9fce3b509cb3ec":{
      "scriptId":"u53"},
    "a9280f3f33eb47d4a9796dbc07f5f7de":{
      "scriptId":"u54"},
    "7f41ef92ff4a41ba87e54f10daf90b28":{
      "scriptId":"u55"},
    "047e21828fc944a98121baad74bab091":{
      "scriptId":"u56"},
    "18473e5d5e984b38a863072f2a60c19e":{
      "scriptId":"u57"},
    "789da28de474452784faaf16091270aa":{
      "scriptId":"u58"},
    "85073eeb15a74ab281b0d75675c55a53":{
      "scriptId":"u59"}}});