$axure.loadCurrentPage({
  "url":"页面_2.html",
  "generationDate":new Date(1402239529303.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"659e5338a87d4d40bc49252cd7d65b47",
    "type":"Axure:Page",
    "name":"页面 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b2a5d9ff740f4b16a655536df9445420",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":10},
            "size":{
              "width":540,
              "height":370}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d99bdc94e774c2c8f225cb4510a01e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":10},
                "size":{
                  "width":540,
                  "height":370}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_2/u0.png"}},
{
          "id":"37df24d358654138b560ed547dcd3ee1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":50},
            "size":{
              "width":470,
              "height":260}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f57e25515e24889adbe61539604d625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":50},
                "size":{
                  "width":470,
                  "height":260}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_2/u2.png"}},
{
          "id":"a87d4b8f8b264f38a932c646dc4a57b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":370,
              "y":62},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8661e70ef40f44eda9856a7aa76b3a19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":370,
                  "y":62},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05cfbb918143466dadcb4c19f61b1ddf",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":110},
            "size":{
              "width":390,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f1de9e2d0d6484eaa23f9cf570bbbda",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dc4cae80edb84fd493ca27797f55b7a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u7.png"}},
{
              "id":"10b902f5374849689dc20027b2ac3d53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c2f0c0078a0743c4b272fd9009a157e6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u7.png"}},
{
              "id":"0413840a75174e43ba6030354cfb227d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"222039f0ef98458c8ef3e28ed996cf8f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u7.png"}},
{
              "id":"138540cd9d24480e8b0f4ae5145ee3ea",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":0},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8981837d528d43548e8300ea883e89bb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":0},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_1/u11.png"}},
{
              "id":"c726b372d1484e4e8274b56adf297ce2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":30},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"501e863c2b2c4d0ea11cd5f83cf6f559",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":30},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_1/u11.png"}},
{
              "id":"281b5c6f81734d45a7dffc423126f915",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":60},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3dd5eec3da1d4cec9a321b88765a3032",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":60},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_1/u11.png"}},
{
              "id":"09d054972bb2402a8d3e1a16d3c74e05",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":169,
                  "y":0},
                "size":{
                  "width":47,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4e7a0baca3d4c94b098168255421926",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":169,
                      "y":0},
                    "size":{
                      "width":47,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u11.png"}},
{
              "id":"b49ba3f7487b480fad5e5d18e67c7119",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":169,
                  "y":30},
                "size":{
                  "width":47,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f0c1fbae78c54396916ba4443ae59c15",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":169,
                      "y":30},
                    "size":{
                      "width":47,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u11.png"}},
{
              "id":"bd00d6a0a54d4d5c9c49a1aa5fbf5b50",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":169,
                  "y":60},
                "size":{
                  "width":47,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d78eeb0acdb6418a85ab77c24c1db350",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":169,
                      "y":60},
                    "size":{
                      "width":47,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u11.png"}},
{
              "id":"bbbb73ef8d9d4642872302121edead40",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":0},
                "size":{
                  "width":65,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e9b77abc9a7f4a5ba04cddbbea855af7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":0},
                    "size":{
                      "width":65,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u15.png"}},
{
              "id":"5a7d0f4ad3954ad89a11cbd7ee25ec89",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":30},
                "size":{
                  "width":65,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d2bd6e03c2c6450d80d887c1f8404ebc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":30},
                    "size":{
                      "width":65,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u15.png"}},
{
              "id":"c875c0bde4694ca5b6c3c8eff499df6b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":60},
                "size":{
                  "width":65,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e6d3507d1c984a86bf0c28a1e92070f0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":60},
                    "size":{
                      "width":65,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u15.png"}},
{
              "id":"73f999d03511423cb6f06c267083153c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":216,
                  "y":0},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2d0d44a7e6d041aa9f6aa1dacbbfff1a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":216,
                      "y":0},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_1/u11.png"}},
{
              "id":"4f3cd7a8e8c048c78a472a4a83ab0389",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":216,
                  "y":30},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"94156748d48941c987979639186e93c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":216,
                      "y":30},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_1/u11.png"}},
{
              "id":"8bcc70981f1945c08dc2d5cbf22ebca1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":216,
                  "y":60},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fdec31b71fe04c55a3096504f23bb492",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":216,
                      "y":60},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_1/u11.png"}},
{
              "id":"895e254727f44b36b7e32782146479a5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":324,
                  "y":0},
                "size":{
                  "width":66,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9f524f6bf2a04ac7b6c5c336385e0d23",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":324,
                      "y":0},
                    "size":{
                      "width":66,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u17.png"}},
{
              "id":"745a65f46b704dee871a4abeea7fe71b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":324,
                  "y":30},
                "size":{
                  "width":66,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"18d9457d1de54a58b1ab0babf281ee33",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":324,
                      "y":30},
                    "size":{
                      "width":66,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u17.png"}},
{
              "id":"aad1af138ef94a1da477da11335a1ab6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":324,
                  "y":60},
                "size":{
                  "width":66,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0a6087c30a3a4985afb1b5488bdd6bde",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":324,
                      "y":60},
                    "size":{
                      "width":66,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u17.png"}},
{
              "id":"9661235a93df4f82a0165f619c8a8cbb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e52bba2b012c422ebf7bd296eaf28ffa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u43.png"}},
{
              "id":"e0db0f170d35496cad84db9b01da363d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":90},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"06a5123d57dd4d79bcd59d8d4fc6f2f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":90},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_1/u35.png"}},
{
              "id":"55137895e3404038a254934b0107e7ad",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":169,
                  "y":90},
                "size":{
                  "width":47,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b6c9a2f697a34855b9d1a04c53d0dd9e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":169,
                      "y":90},
                    "size":{
                      "width":47,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u47.png"}},
{
              "id":"3a2db4bc791a482bbe151140715f9712",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":216,
                  "y":90},
                "size":{
                  "width":43,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1898a094594c4dceae0aa4fb11c7d2ac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":216,
                      "y":90},
                    "size":{
                      "width":43,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_1/u35.png"}},
{
              "id":"0745c238275c4288a1962845b9308ad1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":90},
                "size":{
                  "width":65,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8ee37173967a49f08b027b6cefc349f1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":90},
                    "size":{
                      "width":65,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u51.png"}},
{
              "id":"1a1cbf3a62ee4cc0b53ba56116c95d09",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":324,
                  "y":90},
                "size":{
                  "width":66,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5896d78b056a4bc2b1f6518d17a15f18",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":324,
                      "y":90},
                    "size":{
                      "width":66,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u53.png"}}]},
{
          "id":"bc0dd382e44249edb9331da645e8c73e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":557,
              "y":143},
            "size":{
              "width":41,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"49dcadb12d514946acefccd949c46949",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":557,
              "y":173},
            "size":{
              "width":41,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"41d49e50f85843dab97746ec2882e404",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":557,
              "y":203},
            "size":{
              "width":41,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7ace283398054d37b7655138342f22ae",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":288.5,
              "y":245},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 页面 3 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"页面_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b6531fbf7ace4832a65f27427bd09de9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":431.5,
              "y":245},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 页面 1 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"页面_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "b2a5d9ff740f4b16a655536df9445420":{
      "scriptId":"u0"},
    "2d99bdc94e774c2c8f225cb4510a01e2":{
      "scriptId":"u1"},
    "37df24d358654138b560ed547dcd3ee1":{
      "scriptId":"u2"},
    "3f57e25515e24889adbe61539604d625":{
      "scriptId":"u3"},
    "a87d4b8f8b264f38a932c646dc4a57b5":{
      "scriptId":"u4"},
    "8661e70ef40f44eda9856a7aa76b3a19":{
      "scriptId":"u5"},
    "05cfbb918143466dadcb4c19f61b1ddf":{
      "scriptId":"u6"},
    "2f1de9e2d0d6484eaa23f9cf570bbbda":{
      "scriptId":"u7"},
    "dc4cae80edb84fd493ca27797f55b7a3":{
      "scriptId":"u8"},
    "138540cd9d24480e8b0f4ae5145ee3ea":{
      "scriptId":"u9"},
    "8981837d528d43548e8300ea883e89bb":{
      "scriptId":"u10"},
    "09d054972bb2402a8d3e1a16d3c74e05":{
      "scriptId":"u11"},
    "b4e7a0baca3d4c94b098168255421926":{
      "scriptId":"u12"},
    "73f999d03511423cb6f06c267083153c":{
      "scriptId":"u13"},
    "2d0d44a7e6d041aa9f6aa1dacbbfff1a":{
      "scriptId":"u14"},
    "bbbb73ef8d9d4642872302121edead40":{
      "scriptId":"u15"},
    "e9b77abc9a7f4a5ba04cddbbea855af7":{
      "scriptId":"u16"},
    "895e254727f44b36b7e32782146479a5":{
      "scriptId":"u17"},
    "9f524f6bf2a04ac7b6c5c336385e0d23":{
      "scriptId":"u18"},
    "10b902f5374849689dc20027b2ac3d53":{
      "scriptId":"u19"},
    "c2f0c0078a0743c4b272fd9009a157e6":{
      "scriptId":"u20"},
    "c726b372d1484e4e8274b56adf297ce2":{
      "scriptId":"u21"},
    "501e863c2b2c4d0ea11cd5f83cf6f559":{
      "scriptId":"u22"},
    "b49ba3f7487b480fad5e5d18e67c7119":{
      "scriptId":"u23"},
    "f0c1fbae78c54396916ba4443ae59c15":{
      "scriptId":"u24"},
    "4f3cd7a8e8c048c78a472a4a83ab0389":{
      "scriptId":"u25"},
    "94156748d48941c987979639186e93c5":{
      "scriptId":"u26"},
    "5a7d0f4ad3954ad89a11cbd7ee25ec89":{
      "scriptId":"u27"},
    "d2bd6e03c2c6450d80d887c1f8404ebc":{
      "scriptId":"u28"},
    "745a65f46b704dee871a4abeea7fe71b":{
      "scriptId":"u29"},
    "18d9457d1de54a58b1ab0babf281ee33":{
      "scriptId":"u30"},
    "0413840a75174e43ba6030354cfb227d":{
      "scriptId":"u31"},
    "222039f0ef98458c8ef3e28ed996cf8f":{
      "scriptId":"u32"},
    "281b5c6f81734d45a7dffc423126f915":{
      "scriptId":"u33"},
    "3dd5eec3da1d4cec9a321b88765a3032":{
      "scriptId":"u34"},
    "bd00d6a0a54d4d5c9c49a1aa5fbf5b50":{
      "scriptId":"u35"},
    "d78eeb0acdb6418a85ab77c24c1db350":{
      "scriptId":"u36"},
    "8bcc70981f1945c08dc2d5cbf22ebca1":{
      "scriptId":"u37"},
    "fdec31b71fe04c55a3096504f23bb492":{
      "scriptId":"u38"},
    "c875c0bde4694ca5b6c3c8eff499df6b":{
      "scriptId":"u39"},
    "e6d3507d1c984a86bf0c28a1e92070f0":{
      "scriptId":"u40"},
    "aad1af138ef94a1da477da11335a1ab6":{
      "scriptId":"u41"},
    "0a6087c30a3a4985afb1b5488bdd6bde":{
      "scriptId":"u42"},
    "9661235a93df4f82a0165f619c8a8cbb":{
      "scriptId":"u43"},
    "e52bba2b012c422ebf7bd296eaf28ffa":{
      "scriptId":"u44"},
    "e0db0f170d35496cad84db9b01da363d":{
      "scriptId":"u45"},
    "06a5123d57dd4d79bcd59d8d4fc6f2f7":{
      "scriptId":"u46"},
    "55137895e3404038a254934b0107e7ad":{
      "scriptId":"u47"},
    "b6c9a2f697a34855b9d1a04c53d0dd9e":{
      "scriptId":"u48"},
    "3a2db4bc791a482bbe151140715f9712":{
      "scriptId":"u49"},
    "1898a094594c4dceae0aa4fb11c7d2ac":{
      "scriptId":"u50"},
    "0745c238275c4288a1962845b9308ad1":{
      "scriptId":"u51"},
    "8ee37173967a49f08b027b6cefc349f1":{
      "scriptId":"u52"},
    "1a1cbf3a62ee4cc0b53ba56116c95d09":{
      "scriptId":"u53"},
    "5896d78b056a4bc2b1f6518d17a15f18":{
      "scriptId":"u54"},
    "bc0dd382e44249edb9331da645e8c73e":{
      "scriptId":"u55"},
    "49dcadb12d514946acefccd949c46949":{
      "scriptId":"u56"},
    "41d49e50f85843dab97746ec2882e404":{
      "scriptId":"u57"},
    "7ace283398054d37b7655138342f22ae":{
      "scriptId":"u58"},
    "b6531fbf7ace4832a65f27427bd09de9":{
      "scriptId":"u59"}}});